### ISSUE TITLE
[Bug] Feedback on order confirmation page is not working

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-capybara#391] opened 2020-06-09 11:05 UTC
After placing order, on order confirmation page, user has the possibility to write a feedback but after clinking on 'Send my feedback' button, the message 'Source email address is invalid!' appears and user is not able to send the feedback

## Expected behavior
User should be able to send feedback and the message 'Thank you for sharing your feedback' should appear. 

## Steps to reproduce the issue
1. add any product to the cart
2. go to checkout
3. go through all the checkout steps
4. click 'place the order' button
5. scroll down to the 'What we can improve?' section
6. write feedback
7. click on 'send my feedback' button
8. see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
![feedback](https://user-images.githubusercontent.com/57936972/84140380-d15fa280-aa51-11ea-92cb-ea1d7418dbd5.gif)

**Comment by pkarw** [comment] 2020-06-10 06:31
This is caused by misconfig of the e-mail module is not Capybara's bug - closing for now

**Closed by pkarw** 2020-06-10 06:31 UTC
Labels: bug
