### ISSUE TITLE
No error message when api/order returns 500

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vsf-capybara#212] opened 2020-02-25 15:05 UTC
This is probably some edge case with the payment/shipping combination - however it's ending up with api error and no message. We should show something like "Internal Error while processing your order. Please try again later."

![Screenshot 2020-02-25 16 03 48](https://user-images.githubusercontent.com/211899/75259645-a033cd00-57e8-11ea-89dd-5560ade7b03d.png)

By the way: The problem was with "Authorize.net" payment method that should be disabled in the Magento panel

**Comment by pkarw** [comment] 2020-02-25 15:08
VSF1 displays the following error message (and the user can again click "Place order"):
![Screenshot 2020-02-25 16 06 32](https://user-images.githubusercontent.com/211899/75259859-facd2900-57e8-11ea-8ba6-e29b2c971c91.png)

**Comment by qiqqq** [comment] 2020-03-10 13:42
@pkarw I investigated this issue and the problem is in VueStorefront directly. I create PR there so I am closing this issue:
https://github.com/DivanteLtd/vue-storefront/pull/4167

**Closed by qiqqq** 2020-03-10 13:42 UTC
Labels: 3: Medium complexity, P2: Important, bug
